### **Creating numpy/N-d array**

In [2]:
import numpy as np


In [3]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
type(arr1)

numpy.ndarray

In [6]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
arr5 = np.identity((4))
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7 = np.arange(5,15)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr8 = np.arange(5,15,2)
arr8

array([ 5,  7,  9, 11, 13])

In [16]:
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [18]:
arr10 = arr8.copy()
arr10

array([ 5,  7,  9, 11, 13])

### **propertie and attributes**
- shape
- ndim
- size
- itemsize
- dtype
- astype

In [22]:

arr1.shape


(4,)

In [27]:
arr2.shape
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr2.size

8

In [29]:
arr2.dtype

dtype('int64')

In [30]:
arr2.astype("float")

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [31]:
arr2.dtype

dtype('int64')

In [32]:
arr9.dtype

dtype('float64')

In [33]:
arr9.astype("int")

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])

In [34]:
arr9.dtype

dtype('float64')

### **Python List vs Numpy Array**
- faster
- convenient
- less memory
